### PR TITLE
create articles in coressepondig papers category

### PR DESCRIPTION
**Pull request by nanu-c**
# Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Description

**IMPORTANT TO KNOW**

**CHANGES**

Articles should be published in the custom post type `articles` and the current issue should be applied in the `category_papers`.

**TODO**

The editorial should be published in the custom post type `papers` and the first page should be the featured image. -> should be done in another pr.

# Checklist:

- [x] I have commented my code (or ChatGPT did), particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings, neither in my IDE nor in my browser
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by lebe1 — COMMENTED** [review]
Are you sure you want to leave all of the print statements?
I'm having trouble seeing the results. In my first run I received a valid response with too few categories and no published posts though. In my second and following runs, I receive this message
image

**Comment by nanu-c** [comment]
The category should only be created when it doesn't exist. So maybe you have a category from a previous test? Can you delete them?

Also the logs, it looks on my side like this:

```
[Errno 17] File exists: '/home/nanu/go/src/github.com/augustin-wien/augustin-plugin/sample_data/582_augustin_fertig_kontrolle'
papers_category_id: 22
meta_array: {'category': 0, 'image_id': '', 'image_text': '', 'raw_text': '', 'headlines': [], 'starting_characters': [], 'category_papers': 22}
parse page 1 of 28 pages.
category editorial
Entering parse page once meta_array:
upload post
category_papers_id 22
Reset meta_array
parse page 2 of 28 pages.
category augustiner:in
Entering parse page once meta_array:
upload post
category_papers_id 22
Reset meta_array
parse page 3 of 28 pages.
category einsicht
Entering parse page once meta_array:
Next page needed
parse page 4 of 28 pages.
category das wahre leben
Entering parse page once meta_array:
Extracting raw text with meta_array
upload post
category_papers_id 22
Reset meta_array
parse page 5 of 28 pages.
category cover
Entering parse page once meta_array:
Next page needed
parse page 6 of 28 pages.
category cover
Entering parse page once meta_array:
Extracting raw text with meta_array
Next page needed
parse page 7 of 28 pages.
category cover
Entering parse page once meta_array:
Extracting raw text with meta_array
Next page needed
parse page 8 of 28 pages.
category cover
Entering parse page once meta_array:
Extracting raw text with meta_array
Next page needed
parse page 9 of 28 pages.
category tun & lassen
Entering parse page once meta_array:
Extracting raw text with meta_array
Next page needed
parse page 10 of 28 pages.
category tun & lassen
Entering parse page once meta_array:
Extracting raw text with meta_array
Next page needed
parse page 11 of 28 pages.
category tun & lassen
Entering parse page once meta_array:
Extracting raw text with meta_array
Next page needed
parse page 12 of 28 pages.
category tun & lassen
Entering parse page once meta_array:
Extracting raw text with meta_array
Next page needed
parse page 13 of 28 pages.
category vorstadt
Entering parse page once meta_array:
Extracting raw text with meta_array
Next page needed
parse page 14 of 28 pages.
category vorstadt
Entering parse page once meta_array:
Extracting raw text with meta_array
Next page needed
parse page 15 of 28 pages.
category lokalmatador:in nº
Entering parse page once meta_array:
Extracting raw text with meta_array
Next page needed
INFO:     127.0.0.1:41126 - "POST /upload HTTP/1.1" 200 OK
```

**Comment by nanu-c** [comment]
In the main branch there is the print of the meta_arary in `Entering parse page once meta_array:` to the console that is really poluted

**Review by lebe1 — COMMENTED** [review]
I made some bigger changes moving save_page_as_image() towards the utils.py file and improving the method. Please review this.
Also I would suggest removing the upload_post method or merge them together with a variable to have the possibility to either upload it as a post or as an article. But maybe you had a reason to let it stay like this and have almost the same code twice. What do you think?

**Pull request merged**
